# SF Salaries
***Explore San Francisco city employee salary data***

----

**About Dataset**

One way to understand how a city government works is by looking at who it employs and how its employees are compensated. This data contains the names, job title, and compensation for San Francisco city employees on an annual basis from 2011 to 2014.


Зерттеу нәтижелері төменде жазылған

In [21]:
import kagglehub
import pandas as pd
from kagglehub import KaggleDatasetAdapter

In [4]:
# Load dataset from kaggle
file_path = "Salaries.csv"  # SF - San Francisco

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "kaggle/sf-salaries",
    file_path,
)

/tmp/ipython-input-792790181.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(


100%|██████████| 4.90M/4.90M [00:00<00:00, 57.7MB/s]

Extracting zip of Salaries.csv...



/usr/local/lib/python3.12/dist-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(


In [5]:
df.shape

(148654, 13)

In [6]:
# First 5 row in the dataset
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [7]:
# info about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [8]:
df.describe()

Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

In [13]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [34]:
emp_sal = df[['EmployeeName', 'BasePay', 'OvertimePay', 'OtherPay', 'TotalPay', 'Year']]
emp_sal.head()

EmployeeName    BasePay OvertimePay   OtherPay   TotalPay  Year
0     NATHANIEL FORD  167411.18         0.0  400184.25  567595.43  2011
1       GARY JIMENEZ  155966.02   245131.88  137811.38  538909.28  2011
2     ALBERT PARDINI  212739.13   106088.18    16452.6  335279.91  2011
3  CHRISTOPHER CHONG    77916.0    56120.71   198306.9  332343.61  2011
4    PATRICK GARDNER   134401.6      9737.0  182234.59  326373.19  2011

In [35]:
emp_sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   EmployeeName  148654 non-null  object 
 1   BasePay       148049 non-null  object 
 2   OvertimePay   148654 non-null  object 
 3   OtherPay      148654 non-null  object 
 4   TotalPay      148654 non-null  float64
 5   Year          148654 non-null  int64  
dtypes: float64(1), int64(1), object(4)
memory usage: 6.8+ MB


In [36]:
# String типті санға (float) түрлендіру
emp_sal['BasePay'] = pd.to_numeric(emp_sal['BasePay'], errors='coerce')
emp_sal

/tmp/ipython-input-580655668.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emp_sal['BasePay'] = pd.to_numeric(emp_sal['BasePay'], errors='coerce')


EmployeeName    BasePay   OvertimePay      OtherPay   TotalPay  \
0          NATHANIEL FORD  167411.18           0.0     400184.25  567595.43   
1            GARY JIMENEZ  155966.02     245131.88     137811.38  538909.28   
2          ALBERT PARDINI  212739.13     106088.18       16452.6  335279.91   
3       CHRISTOPHER CHONG   77916.00      56120.71      198306.9  332343.61   
4         PATRICK GARDNER  134401.60        9737.0     182234.59  326373.19   
...                   ...        ...           ...           ...        ...   
148649      Roy I Tillery       0.00          0.00          0.00       0.00   
148650       Not provided        NaN  Not Provided  Not Provided       0.00   
148651       Not provided        NaN  Not Provided  Not Provided       0.00   
148652       Not provided        NaN  Not Provided  Not Provided       0.00   
148653          Joe Lopez       0.00          0.00       -618.13    -618.13   

        Year  
0       2011  
1       2011  
2       2011  
3       2011  
4       2011  
...      ...  
148649  2014  
148650  2014  
148651  2014  
148652  2014  
148653  2014  

[148654 rows x 6 columns]

In [37]:
emp_sal['BasePay'].fillna(emp_sal['BasePay'].mean(), inplace=True)

/tmp/ipython-input-4073885104.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_sal['BasePay'].fillna(emp_sal['BasePay'].mean(), inplace=True)
/tmp/ipython-input-4073885104.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emp_sal['BasePay'].fillna(emp_sal['BasePay'].mean(), inplace=True)


In [38]:
emp_sal['BasePay'].isna().sum()

np.int64(0)

In [39]:
emp_sal['OvertimePay'] = pd.to_numeric(emp_sal['OvertimePay'], errors='coerce')
emp_sal['OtherPay'] = pd.to_numeric(emp_sal['OtherPay'], errors='coerce')
emp_sal[['OvertimePay', 'OtherPay']].isna().sum()

/tmp/ipython-input-1739398807.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emp_sal['OvertimePay'] = pd.to_numeric(emp_sal['OvertimePay'], errors='coerce')
/tmp/ipython-input-1739398807.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emp_sal['OtherPay'] = pd.to_numeric(emp_sal['OtherPay'], errors='coerce')


OvertimePay    4
OtherPay       4
dtype: int64

In [40]:
emp_sal['OvertimePay'].fillna(emp_sal['OvertimePay'].mean(), inplace=True)
emp_sal['OtherPay'].fillna(emp_sal['OtherPay'].mean(), inplace=True)
emp_sal.isna().sum()

/tmp/ipython-input-1916915795.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_sal['OvertimePay'].fillna(emp_sal['OvertimePay'].mean(), inplace=True)
/tmp/ipython-input-1916915795.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emp_sal['OvertimePay'].fillna(emp_sal['OvertimePay'].mean(), inplace=True)
/tmp/ipython-input-1916915795.p

EmployeeName    0
BasePay         0
OvertimePay     0
OtherPay        0
TotalPay        0
Year            0
dtype: int64

Осы жерге дейін жұмысым өзіме керек бағандарды таңдап, оларды тазалау болды. Бос орындарды анықтап оларды орташа мәнмен толтырдым

# Төмендегі зерттеу бойынша қорытынды
1.  Базалық тұрақты орташа төлем 2011-2014 жылдары 63595 доллардан 66564 долларға дейін көтерілген
2.  Қосымша жұмыс уақыты үшін баға көтерілді деп айтуға негіз жоқ, себебі бұл адамдардың бір ситуацияға, мерекелік күндерде болмаса өз бетінше көп табамын деген оймен көп уақыт жұмыс істеуіне байланысты яғни жай ғана қосымша табыс
3.  Өзге табыс түрлері бойынша керісінше 3617 доллардан 3505 долларға төмендеген, яғни бұл компания төлейтін оклад деп есептесек ондай компания табысы 2011-2014 жылдары төмендегені байқалады себебі оклад бұл түскен пайданың бір бөлігін жұмысшыларға бөліп беру

In [41]:
emp_sal.groupby(by='Year')[['BasePay', 'OvertimePay', 'OtherPay', 'TotalPay']].mean()

BasePay  OvertimePay     OtherPay      TotalPay
Year                                                      
2011  63595.956517  4531.065429  3617.081926  71744.103871
2012  65436.406857  5023.417824  3653.437583  74113.262265
2013  69576.866579  5281.641980  3819.969007  77611.443142
2014  66564.396851  5401.958490  3505.436291  75463.918140

from matplotlib import pyplot as plt
_df_0['BasePay'].plot(kind='hist', bins=20, title='BasePay')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['OvertimePay'].plot(kind='hist', bins=20, title='OvertimePay')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['OtherPay'].plot(kind='hist', bins=20, title='OtherPay')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['TotalPay'].plot(kind='hist', bins=20, title='TotalPay')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='BasePay', y='OvertimePay', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='OvertimePay', y='OtherPay', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='OtherPay', y='TotalPay', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['OvertimePay']
  ys = series['BasePay']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('OvertimePay', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('OvertimePay')
_ = plt.ylabel('BasePay')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['OvertimePay']
  ys = series['OtherPay']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('OvertimePay', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('OvertimePay')
_ = plt.ylabel('OtherPay')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['OvertimePay']
  ys = series['TotalPay']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('OvertimePay', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('OvertimePay')
_ = plt.ylabel('TotalPay')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['OvertimePay']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'OvertimePay'}, axis=1)
              .sort_values('OvertimePay', ascending=True))
  xs = counted['OvertimePay']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('OvertimePay', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('OvertimePay')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_11['BasePay'].plot(kind='line', figsize=(8, 4), title='BasePay')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['OvertimePay'].plot(kind='line', figsize=(8, 4), title='OvertimePay')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['OtherPay'].plot(kind='line', figsize=(8, 4), title='OtherPay')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['TotalPay'].plot(kind='line', figsize=(8, 4), title='TotalPay')
plt.gca().spines[['top', 'right']].set_visible(False)

In [50]:
group_by_name = emp_sal.groupby(by='Year')['EmployeeName'].count()
group_by_name

Year
2011    36159
2012    36766
2013    37606
2014    38123
Name: EmployeeName, dtype: int64

In [56]:
group_by_salary = emp_sal.groupby(by = 'Year')['TotalPay'].sum()
group_by_salary

Year
2011    2.594195e+09
2012    2.724848e+09
2013    2.918656e+09
2014    2.876911e+09
Name: TotalPay, dtype: float64

In [67]:
salemp = pd.merge(group_by_name, group_by_salary, on = 'Year')
salemp['EverySalary'] = round(salemp['TotalPay'] / salemp['EmployeeName'], 2)
salemp['PercentEverySalary'] = round(salemp['EverySalary'] / salemp.iloc[0, 2], 2)
salemp

EmployeeName      TotalPay  EverySalary  PercentEverySalary
Year                                                             
2011         36159  2.594195e+09     71744.10                1.00
2012         36766  2.724848e+09     74113.26                1.03
2013         37606  2.918656e+09     77611.44                1.08
2014         38123  2.876911e+09     75463.92                1.05

1.  Жоғарыдағы зерттеуге сәйкес мен әр жылғы қызметкерлер санын және олардың жылдық табысын есептедім, сонымен осы жылдық табысты сол жылғы қызметкерлер санына бөлу арқылы әр жылдағы 1 адамның орташа табысын шығардым
2.  Зерттеуге сәйкес әр адамға шаққандағы орташа жылдық табыс 2011-2014 жылдары 71744.10 доллардан 75463.92 долларға дейін көтерілген
3.  Яғни 2011 жылмен салыстырғанда 2012 жылы 3%-ға, 2013 жылы 8%-ға, 2014 жылы 5%-ға өскен
4.  2014 жылы 2013 ке қарағанда өсім аз осыдан қорытындылай келе 2013 ең өнімді жыл болып табылады

In [77]:
df.groupby(['Year', 'Status'])['TotalPay'].sum()

Year  Status
2014  FT        2.311698e+09
      PT        5.652133e+08
Name: TotalPay, dtype: float64

1.  Статус тек 2014 жылы пайда болған, себебі басқа жылдар бойынша топтау нәтижелері бос немесе болмаған